import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import styles from "./page.module.css";
import Link from "next/link";
import Footer from "./components/Footer/Footer";
import SocialIcons from "./components/Footer/Socials/Socials";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const adobeKey = process.env.ADOBE_KEY;

  return (
    <html lang="en">
      <head>
        {adobeKey ? (
          <>
            <link rel="preconnect" href="https://use.typekit.net" />
            <link rel="stylesheet" href={adobeKey} />
          </>
        ) : null}
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className={styles.siteHeader}>
          <Link href="/" className={styles.heroLogoLink} aria-label="Go to homepage">
            <img
              src="/images/Jessie_Krebs_Color.png"
              alt="Jessie Krebs"
              className={`img-fluid ${styles.heroLogo} center`}
            />
          </Link>

          <div className={styles.topLeftLinks}>
            <Link href="/packing_list">General Packing List</Link>
            <Link href="/online_learning">Online Learning</Link>
          </div>

          <div className={`${styles.topRightLogos} z-10 mobileInvisible`}>
            <SocialIcons />
          </div>

          <div className={styles.asSeenWrap}>
            <h1>As Seen On</h1>
            <div className={styles.logoGrid}>
              <img src="/logo_references/alone-s9-logo-black.png" alt="Alone S9 Logo" />
              <img src="/logo_references/National_Geographic-Logo.png" alt="National Geographic Logo" />
              <img src="/logo_references/MasterClass-logo.png" alt="MasterClass Logo" />
              <img className={styles.mobileInvisible} src="/logo_references/outdoor-life-vector-logo.png" alt="Outdoor Life Logo" />
              <img src="/logo_references/discovery.png" alt="Discovery Logo" />
              <img className={styles.mobileInvisible} src="/logo_references/backPacker.png" alt="Backpacker Logo" />
              <img className={styles.mobileInvisible} src="/logo_references/Durango-Herald.png" alt="Durango Herald Logo" />
              <img className={styles.mobileInvisible} src="/logo_references/Black_Fox.png" alt="Black Fox Logo" />
            </div>
          </div>
        </div>
        {children}
        <Footer isSmall={true} />
      </body>
    </html>
  );
}
